### ISSUE TITLE
can't find LFVideoEditingController.h

### ISSUE THREAD

**Issue by ghost** [lincf0912/LFCameraPickerController#2]
在pods中没有发现LFVideoEditingController.h文件！

**Comment by lincf0912** [comment]
我使用demo测试是有的，请你再pod update一下。
<img width="229" alt="2017-08-23 10 37 37" src="https://user-images.githubusercontent.com/10151410/29596318-2f24308a-87ef-11e7-9aad-56532bcc989f.png">
