### ISSUE TITLE
拍摄，拍照方向有问题

### ISSUE THREAD

**Issue by astralchen** [lincf0912/LFCameraPickerController#5]
🔐系统方向锁定打开，再去拍摄，拍照方向有问题

**Comment by lincf0912** [comment]
竖屏拍摄、拍照，有什么问题？
原生相机是不受系统方向锁影响的

**Comment by astralchen** [comment]
拍照 拍摄 受系统方向锁影响的

**Comment by lincf0912** [comment]
LFCameraPickerController 是受系统方向锁影响的，开启了方向锁，等同于竖屏

**Comment by lincf0912** [comment]
如果你更喜欢像原生相机一样不受系统方向锁影响。
可以fork LFCameraPickerController处理屏幕方向修改为重力感应就可以了（参考：http://www.jianshu.com/p/692e7a490747）

**Comment by astralchen** [comment]
用于用户来说，横拍和竖屏使用正常，有些用户会开启系统方向锁， 能否调整像微信和原生相机一样不受系统方向锁影响，因为拍摄视频大家都倾向横屏拍摄

**Comment by lincf0912** [comment]
好的，这将是大势所趋。

**Comment by lincf0912** [comment]
Modified it in version 1.0.5.1, pls pod update
