### ISSUE TITLE
通过 pod 导入LFCameraPickerController Framework，加载图片资源路径有问题

### ISSUE THREAD

**Issue by astralchen** [lincf0912/LFCameraPickerController#6]
应将此处
#define LFCamera_bundleImageNamed(name) [UIImage imageNamed:[NSString stringWithFormat:@"LFCameraPickerController.bundle/%@", name]]
替换成
#define LFCamera_bundleImageNamed(name) [UIImage imageNamed:[NSString stringWithFormat:@"LFCameraPickerController.bundle/%@",name] inBundle:[NSBundle bundleForClass:[LFCameraPickerController class]] compatibleWithTraitCollection:nil]

**Comment by lincf0912** [comment]
cocoapod 会通过shell 将资源文件拷贝到你的项目中。

**Comment by astralchen** [comment]
Podfile 文件 配置 use_frameworks!,会使图片资源存放图片路径不一样。 你的代码是加载 main bundle中的图片资源，但图片资源在 LFCameraPickerController framework bundle 中，导致加载不到图片资源

**Comment by lincf0912** [comment]
这个脚本会在编译时将cocoapod的资源文件拷贝到项目 即 main bundle.

我越听越觉得你不是用cocoapod 而是手动导入。😉

**Comment by lincf0912** [comment]
[版本1.1.0](https://github.com/lincf0912/LFCameraPickerController/releases/tag/1.1.0)
Podfile文件配置 use_frameworks! 不会生成脚本将资源文件拷贝到项目中。
感谢你的反馈。
