### ISSUE TITLE
外部音频恢复问题

### ISSUE THREAD

**Issue by charlesYun** [lincf0912/LFCameraPickerController#7]
虽然在dealloc里面加了
[[AVAudioSession sharedInstance] setActive:NO withOptions:AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation error:nil]

但是在拍照或者录像后   dismiss 外部音频并没有恢复

**Comment by charlesYun** [comment]
还会抛出错误
AVAudioSession.mm:997:-[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

**Comment by lincf0912** [comment]
更新[版本1.1.2](https://github.com/lincf0912/LFCameraPickerController/releases/tag/1.1.2)
<img width="429" alt="image" src="https://user-images.githubusercontent.com/10151410/79557482-355e8e00-80d5-11ea-85ca-30f88dcb29d5.png">
