### ISSUE TITLE
测试发现有时候录制视频完成，预览时变成一张图片了

### ISSUE THREAD

**Issue by charlesYun** [lincf0912/LFCameraPickerController#8]
测试发现有时候录制视频完成，预览时变成一张图片了，暂时没发现规律，iphone6测试偶发。

**Comment by lincf0912** [comment]
我会在解析视频那里加强判断。或许是视频解析有问题而界面没有提示。

发自我的iPhone

**Comment by charlesYun** [comment]
那要怎么解决呢？等你的新版本吗？


Caoyunxiao


在2020年05月19日 11:26，Lam<notifications@github.com> 写道：

我会在解析视频那里加强判断。或许是视频解析有问题而界面没有提示。

发自我的iPhone

**Comment by lincf0912** [comment]
点一下是拍照；长按才是录视频。
你如果只要求录视频，可以设置属性`cameraType = LFCameraType_Video`来避免可能会拍照的情况。

**Comment by charlesYun** [comment]
这里都需要的，操作上没搞错，确实是录制视频，进度都在走，偶发录制完成 预览界面变一张照片了，iPhone6


Caoyunxiao


在2020年05月19日 16:17，Lam<notifications@github.com> 写道：

点一下是拍照；长按才是录视频。
你如果只要求录视频，可以设置属性cameraType = LFCameraType_Video来避免可能会拍照的情况。

**Comment by lincf0912** [comment]
好的。我下一个版本修复它。

发自我的iPhone

**Comment by charlesYun** [comment]
好的，感谢


Caoyunxiao


在2020年05月19日 18:13，Lam<notifications@github.com> 写道：

好的。我下一个版本修复它。

发自我的iPhone

**Comment by lincf0912** [comment]
请更新[版本1.1.5](https://github.com/lincf0912/LFCameraPickerController/releases/tag/1.1.5)

**Comment by charlesYun** [comment]
OK
